name = "LibCURL"
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.5.2"

[deps]
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[compat]
LibCURL_jll = "7.68"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
