[general]
library_name = "libcurl"
use_julia_native_enum_type = true
use_deterministic_symbol = true
auto_mutability = true

printer_blacklist = [
    "CURL_SUFFIX_CURL_OFF_T",
    "CURL_SUFFIX_CURL_OFF_TU",
    "CURL_ZERO_TERMINATED",
]

[codegen]
use_ccall_macro = true
wrap_variadic_function = true

[codegen.macro]
macro_mode = "basic"